version: '3.8'

# Services
services:
  # Server service
  server:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb+srv://vaideesh4_db_user:Coolba999@onco-lens-cluster.guaxmpg.mongodb.net/onco-lens?appName=onco-lens-cluster
      REDIS_URL: redis://redis:6379
      CLIENT_ORIGIN: http://localhost
      NODE_ENV: development
    depends_on:
      - mongodb

  # Client service
  client:
    build:
      context: ./frontend/onco-lens/
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8000
        VITE_PYTHON_API_URL: http://localhost:8001

    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - server

  # Database service
  mongodb:
    image: mongo:latest
    container_name: mongodb_server

    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD

    ports:
      - "27017:27017"

    volumes:
      - ./../mydata:/data/db
  
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
  
  python-backend:
    build:
      context: ./backend/api/               # correct path from root
      dockerfile: Dockerfile
    container_name: python_backend
    ports:
      - "8001:8001"            # host:container
    volumes:
      - ./backend/api:/app             # correct path for live reload
    environment:
      - PYTHONUNBUFFERED=1

# Volumes define
volumes: 
  mydata: